on:
  push:
    branches:
      - 'epcc'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GPR_USER }}
          # Cannot use GITHUB_TOKEN to push to GHCR
          password: ${{ secrets.GPR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/covid-policy-modelling/web-ui/web-ui:latest
